 /*
  * Copyright (c) 2025 Huawei Device Co., Ltd.
  * Licensed under the MIT License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *     https://github.com/react-native-sensors/react-native-sensors/blob/master/LICENSE
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */

import { RNVLCPackage } from './src/main/ets/RNVLCPackage'
export * from "./src/main/ets/RNVLC"
export default RNVLCPackage